pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - ocean.pangeo.io
        letsencrypt:
          contactEmail: raphael.dussin@gmail.com
      service:
        loadBalancerIP: 34.66.6.21
