# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: http://web-public-icesat2-prod-dask-gateway
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://aws-uswest2.pangeo.io/services/dask-gateway"
        DASK_GATEWAY__PROXY_ADDRESS: "tls://scheduler-public-icesat2-prod-dask-gateway:8786"
    proxy:
      https:
        hosts:
          - aws-uswest2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
    auth:
      github:
        callbackUrl: "https://aws-uswest2.pangeo.io/hub/oauth_callback"
